### ISSUE TITLE
lista

### ISSUE THREAD

**Issue by nelsonbolanoscr** [ericksc/biblioteca#1]
https://github.com/ericksc/biblioteca/blob/05cf0aa7f1200748c900abbc9077e77f230e4eaf/mis_funciones.py#L32

En esa linea 32 de la funcion seleccionar_columna, un argumento se llama lista, de donde viene eso? o ese es nombre de la variable que debo asignar?

**Comment by nelsonbolanoscr** [comment]
ya vi donde se invoca.

**Comment by ericksc** [comment]
Básicamente es un parámetro o argumento de la función.

En el contexto
 Lista sería una lista de reglones. Nótese lo que señalas es la definición de la función.

Cual se llamada allí se le pone el dato que ocupes procesar.  

Es importante que uses el debugger para que lo veas.
